# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_VarFactory', [dirname(__file__)])
        except ImportError:
            import _VarFactory
            return _VarFactory
        if fp is not None:
            try:
                _mod = imp.load_module('_VarFactory', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _VarFactory = swig_import_helper()
    del swig_import_helper
else:
    import _VarFactory
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _VarFactory.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _VarFactory.SwigPyIterator_value(self)
    def incr(self, n=1): return _VarFactory.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _VarFactory.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _VarFactory.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _VarFactory.SwigPyIterator_equal(self, *args)
    def copy(self): return _VarFactory.SwigPyIterator_copy(self)
    def next(self): return _VarFactory.SwigPyIterator_next(self)
    def __next__(self): return _VarFactory.SwigPyIterator___next__(self)
    def previous(self): return _VarFactory.SwigPyIterator_previous(self)
    def advance(self, *args): return _VarFactory.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _VarFactory.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _VarFactory.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _VarFactory.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _VarFactory.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _VarFactory.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _VarFactory.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _VarFactory.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class VarFactory(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VarFactory, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VarFactory, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _VarFactory.new_VarFactory()
        try: self.this.append(this)
        except: self.this = this
    def fluxVar(self, *args): return _VarFactory.VarFactory_fluxVar(self, *args)
    def test(self, *args): return _VarFactory.VarFactory_test(self, *args)
    def trial(self, *args): return _VarFactory.VarFactory_trial(self, *args)
    def testIDs(self): return _VarFactory.VarFactory_testIDs(self)
    def trialIDs(self): return _VarFactory.VarFactory_trialIDs(self)
    def fieldVars(self): return _VarFactory.VarFactory_fieldVars(self)
    def fluxVars(self): return _VarFactory.VarFactory_fluxVars(self)
    def traceVars(self): return _VarFactory.VarFactory_traceVars(self)
    def testVar(self, *args): return _VarFactory.VarFactory_testVar(self, *args)
    def fieldVar(self, *args): return _VarFactory.VarFactory_fieldVar(self, *args)
    def traceVar(self, *args): return _VarFactory.VarFactory_traceVar(self, *args)
    __swig_destroy__ = _VarFactory.delete_VarFactory
    __del__ = lambda self : None;
VarFactory_swigregister = _VarFactory.VarFactory_swigregister
VarFactory_swigregister(VarFactory)

# This file is compatible with both classic and new-style classes.


